### ISSUE TITLE
Metronome broken

### ISSUE THREAD

**Issue by momentarylapse** [momentarylapse/tsunami#17]
Um, I recently broke the metronome (devel branch only)!

Symptoms: a metronome track will sound horrible.

Cause: I have not fully made up my mind about the internal design - beats as time points vs beats as time ranges.

Will fix this soon

**Comment by ErinaceusLinnaeus** [comment]
Up until now Metronoms have always sounded horrible.
This will be the first ever beautiful sounding metronom after the fix.

**Comment by momentarylapse** [comment]
Oh, so no pressure then... :P

I fixed the (technical) bug and it works again.

Concerning the beauty... you can always select a different synthesizer for the metronome track, e.g. use some recorded wave files. And feel free to suggest improvements to how it should sound by default. Right now, it is just a simple equation making a "pick puck puck puck" sound.

**Comment by momentarylapse** [comment]
Some internal design, in case anyone wants to know

The old design:
* beats used to be simple points in time
* data pipelines will send small chunks of audio/midi/beat data between modules
  * very small and some chunks might not contain a single beat

Last month I wrote some modules that needed to continuously track time even "between beats" and changed the design:
* beats cover the whole time range until the next beat
* might be sent repeatedly in multiple chunks while still "active"
  * very messy to handle, needed complicated updates to all modules that handle beats (-> bug)

Now I switched back to beats as simple points in time. And to keep track of continuous time, I now insert a special type of beat containing timer info at the end of each data chunk. Modules will ignore this by default, because they already have to filter the relevant beat types. This makes the whole logic much simpler.

**Comment by ErinaceusLinnaeus** [comment]
I suggest a built-in human counting feature (wav library). Different voices, maybe even different languages.

I had good results playing/recording along a human voice counting. It keeps you in tempo, but is not as strict...leaves you a bit wiggle room and the recording comes out as less robot-like...more feeling.
