### ISSUE TITLE
Mandala-plugin : mismatched triggers

### ISSUE THREAD

**Issue by ErinaceusLinnaeus** [momentarylapse/tsunami#27]
Physical triggers # in the plugin
Rim 1            -      Rim 8
Rim 2           -      nix
Rim 3           -      nix
Rim 4           -      nix
Rim 5           -      nix
Rim 6           -      nix
Rim 7           -      nix
Rim 8          -      Rim 9
Rim 9          -      nix
Zone 1        -      Rim 1
Zone 2       -      Rim 2
Zone 3       -      Rim 3
Zone 4       -      Rim 4

Mandala's (factory setting) midi notes are:

Rim 1            -      60
Rim 2           -      62
Rim 3           -      64
Rim 4           -      65
Rim 5           -      67
Rim 6           -      69
Rim 7           -      71
Rim 8          -      72
Rim 9          -      84
Zone 1        -      48
Zone 2       -      50
Zone 3       -      52
Zone 4       -      53

**Comment by momentarylapse** [comment]
Merged #28, should work now. Thanks for the work!
